vim.opt.nu = true
-- vim.opt.relativenumber = true
vim.opt.scrolloff = 8
vim.opt.updatetime = 250
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.hlsearch = false
vim.opt.incsearch = true
vim.opt.clipboard = "unnamedplus"
vim.opt.colorcolumn = "99999"
vim.opt.fileencoding = "utf-8"
vim.opt.ignorecase = false
vim.opt.mouse = "a"
vim.opt.smartindent = false
vim.opt.splitbelow = false
vim.opt.splitright = true
vim.opt.numberwidth = 4
vim.opt.cmdheight = 1
vim.opt.spell = false
vim.opt.spelllang = ""
vim.o.guifont = "Sarasa Term SC Nerd:h13"
vim.opt.cursorline = true
vim.g.markdown_syntax_conceal = 0
vim.g.neovide_refresh_rate = 60
vim.g.neovide_refresh_rate_idle = 5
-- vim.g.neovide_fullscreen = true
vim.cmd([[autocmd ColorScheme * highlight Comment guifg=#9ACD32]]) -- 修改注释颜色
vim.api.nvim_create_autocmd("FileType", {
	pattern = { "cpp" },
	callback = function()
		vim.bo.expandtab = true -- UseTab: Never
		vim.bo.shiftwidth = 2 -- IndentWidth: 2
		vim.bo.tabstop = 2 -- TabWidth: 2
		vim.bo.softtabstop = 2 -- 编辑时使用 2 个空格代替 Tab
		vim.bo.smartindent = true -- 启用智能缩进（也可用 cindent）
	end,
})
